#!/bin/sh
# Daily Postgres + app-data backups for the `backup` compose service (busybox sh).
#
#   loop            (default) wait for BACKUP_TIME_UTC every day and run a backup
#   once            run one backup now
#   list            list local backups (and remote ones when S3 is configured)
#   fetch <path>    download <path> (relative to the bucket prefix, e.g.
#                   daily/openmuse-20260923T000000Z.dump) into /backups/restore/
#   s3-check        verify the S3 credentials and bucket
#
# Local layout (volume `backups`, mounted at /backups):
#   daily/openmuse-<UTC>.dump      pg_dump -Fc, newest BACKUP_KEEP_DAILY kept (default 7)
#   daily/app-data-<UTC>.tar.gz    session-signing-key + uploaded PDFs (no PGlite dir)
#   weekly/                        hard links of the BACKUP_WEEKLY_DAY backup, newest
#                                  BACKUP_KEEP_WEEKLY kept (default 4); no extra disk
#   .status                        "ok|fail <epoch> <detail>", read by the monitor
#
# Tehran is UTC+03:30 without DST, so 03:30 Asia/Tehran is 00:00 UTC.
set -eu

BACKUP_DIR="${BACKUP_DIR:-/backups}"
APP_DATA_DIR="${APP_DATA_DIR:-/appdata}"
BACKUP_TIME_UTC="${BACKUP_TIME_UTC:-00:00}"
BACKUP_KEEP_DAILY="${BACKUP_KEEP_DAILY:-7}"
BACKUP_KEEP_WEEKLY="${BACKUP_KEEP_WEEKLY:-4}"
BACKUP_WEEKLY_DAY="${BACKUP_WEEKLY_DAY:-5}" # 1=Monday … 5=Friday (UTC date)
BACKUP_APP_DATA="${BACKUP_APP_DATA:-1}"
BACKUP_MIN_FREE_MB="${BACKUP_MIN_FREE_MB:-500}"
BACKUP_S3_PREFIX="${BACKUP_S3_PREFIX:-openmuse}"
BACKUP_S3_RETENTION_DAYS="${BACKUP_S3_RETENTION_DAYS:-30}"

log() { echo "[backup] $(date -u +%Y-%m-%dT%H:%M:%SZ) $*"; }

s3_enabled() {
  [ -n "${BACKUP_S3_ENDPOINT:-}" ] && [ -n "${BACKUP_S3_BUCKET:-}" ] &&
    [ -n "${BACKUP_S3_ACCESS_KEY:-}" ] && [ -n "${BACKUP_S3_SECRET_KEY:-}" ]
}

# rclone reads the remote "arvan" from env; no config file (and no secrets) on disk.
s3_env() {
  export RCLONE_CONFIG_ARVAN_TYPE=s3
  export RCLONE_CONFIG_ARVAN_PROVIDER="${BACKUP_S3_PROVIDER:-ArvanCloud}"
  export RCLONE_CONFIG_ARVAN_ENDPOINT="$BACKUP_S3_ENDPOINT"
  export RCLONE_CONFIG_ARVAN_ACCESS_KEY_ID="$BACKUP_S3_ACCESS_KEY"
  export RCLONE_CONFIG_ARVAN_SECRET_ACCESS_KEY="$BACKUP_S3_SECRET_KEY"
  export RCLONE_CONFIG_ARVAN_ACL=private
  export RCLONE_CONFIG_ARVAN_NO_CHECK_BUCKET=true
  export RCLONE_CONFIG=/dev/null
}

remote() { echo "arvan:${BACKUP_S3_BUCKET}/${BACKUP_S3_PREFIX}${1:+/$1}"; }

status() { # status ok|fail detail
  printf '%s %s %s\n' "$1" "$(date -u +%s)" "$2" >"$BACKUP_DIR/.status.tmp"
  mv "$BACKUP_DIR/.status.tmp" "$BACKUP_DIR/.status"
}

prune_local() { # prune_local dir pattern keep
  # Names embed the UTC timestamp, so a reverse name sort is newest-first.
  # shellcheck disable=SC2010 # names are generated by this script
  ls -1 "$1" 2>/dev/null | grep -E "$2" | sort -r | tail -n +"$(($3 + 1))" | while read -r old; do
    log "removing old local backup $1/$old"
    rm -f "$1/$old"
  done
}

run_backup() {
  mkdir -p "$BACKUP_DIR/daily" "$BACKUP_DIR/weekly"
  free_mb=$(df -Pm "$BACKUP_DIR" | awk 'NR==2 {print $4}')
  if [ "${free_mb:-0}" -lt "$BACKUP_MIN_FREE_MB" ]; then
    status fail "low-disk ${free_mb}MB free"
    log "ERROR: only ${free_mb} MB free (< $BACKUP_MIN_FREE_MB MB); backup skipped"
    return 1
  fi

  stamp=$(date -u +%Y%m%dT%H%M%SZ)
  dump="$BACKUP_DIR/daily/openmuse-$stamp.dump"
  log "pg_dump -> $dump"
  if ! pg_dump -Fc -Z 6 -f "$dump.partial"; then
    rm -f "$dump.partial"
    status fail "pg_dump"
    log "ERROR: pg_dump failed"
    return 1
  fi
  mv "$dump.partial" "$dump"
  files="$dump"

  # postgres/ is the embedded PGlite dir, unused when DATABASE_URL points at Postgres.
  # shellcheck disable=SC2010 # plain names created by the app
  entries=$(ls -A "$APP_DATA_DIR" 2>/dev/null | grep -vx postgres || true)
  if [ "$BACKUP_APP_DATA" = 1 ] && [ -n "$entries" ]; then
    tarball="$BACKUP_DIR/daily/app-data-$stamp.tar.gz"
    log "app-data -> $tarball"
    # shellcheck disable=SC2086 # entries are plain file names created by the app
    if tar czf "$tarball.partial" -C "$APP_DATA_DIR" $entries; then
      mv "$tarball.partial" "$tarball"
      files="$files $tarball"
    else
      rm -f "$tarball.partial"
      status fail "app-data tar"
      log "ERROR: app-data archive failed"
      return 1
    fi
  fi

  # One weekly copy per week, even when `once` is also run by hand on that day.
  if [ "$(date -u +%u)" = "$BACKUP_WEEKLY_DAY" ] &&
    [ -z "$(find "$BACKUP_DIR/weekly" -name 'openmuse-*.dump' -mtime -6 2>/dev/null)" ]; then
    for f in $files; do ln -f "$f" "$BACKUP_DIR/weekly/$(basename "$f")"; done
    log "weekly copy kept"
  fi
  prune_local "$BACKUP_DIR/daily" '^openmuse-.*\.dump$' "$BACKUP_KEEP_DAILY"
  prune_local "$BACKUP_DIR/daily" '^app-data-.*\.tar\.gz$' "$BACKUP_KEEP_DAILY"
  prune_local "$BACKUP_DIR/weekly" '^openmuse-.*\.dump$' "$BACKUP_KEEP_WEEKLY"
  prune_local "$BACKUP_DIR/weekly" '^app-data-.*\.tar\.gz$' "$BACKUP_KEEP_WEEKLY"

  if s3_enabled; then
    s3_env
    for f in $files; do
      log "upload $(basename "$f") -> $(remote daily)/"
      if ! rclone copy --retries 5 --low-level-retries 10 "$f" "$(remote daily)"; then
        status fail "s3-upload"
        log "ERROR: upload to S3 failed (local copy kept)"
        return 1
      fi
    done
    log "pruning remote backups older than ${BACKUP_S3_RETENTION_DAYS}d"
    rclone delete --min-age "${BACKUP_S3_RETENTION_DAYS}d" "$(remote daily)" || log "WARN: remote prune failed"
  else
    log "S3 not configured; local backups only"
  fi

  size=$(du -h "$dump" | cut -f1)
  status ok "$(basename "$dump") $size"
  log "done ($size); local usage: $(du -sh "$BACKUP_DIR" | cut -f1)"
}

seconds_until() { # seconds until next HH:MM UTC
  # Strip leading zeros: shell arithmetic reads "08" as invalid octal.
  hh=$(echo "${1%%:*}" | sed 's/^0*//')
  mm=$(echo "${1##*:}" | sed 's/^0*//')
  target=$((${hh:-0} * 3600 + ${mm:-0} * 60))
  now=$(date -u +%s)
  today=$((now - now % 86400))
  next=$((today + target))
  [ "$next" -gt "$now" ] || next=$((next + 86400))
  echo $((next - now))
}

cmd="${1:-loop}"
case "$cmd" in
  loop)
    [ "${BACKUP_ENABLED:-1}" = 1 ] || {
      log "BACKUP_ENABLED=0; idle"
      exec sleep 2147483647
    }
    log "scheduled daily at $BACKUP_TIME_UTC UTC; keep ${BACKUP_KEEP_DAILY} daily/${BACKUP_KEEP_WEEKLY} weekly; S3: $(s3_enabled && echo on || echo off)"
    [ "${BACKUP_RUN_ON_START:-0}" = 1 ] && { run_backup || true; }
    while :; do
      wait_s=$(seconds_until "$BACKUP_TIME_UTC")
      log "next backup in ${wait_s}s"
      sleep "$wait_s"
      run_backup || true
      sleep 60
    done
    ;;
  once) run_backup ;;
  list)
    echo "== local ($BACKUP_DIR)"
    ls -lh "$BACKUP_DIR/daily" "$BACKUP_DIR/weekly" 2>/dev/null || true
    [ -f "$BACKUP_DIR/.status" ] && echo "status: $(cat "$BACKUP_DIR/.status")"
    if s3_enabled; then
      s3_env
      echo "== remote $(remote)"
      rclone lsl "$(remote)" || true
    fi
    ;;
  fetch)
    [ -n "${2:-}" ] || {
      echo "usage: fetch daily/<file>" >&2
      exit 2
    }
    s3_enabled || {
      echo "S3 is not configured" >&2
      exit 1
    }
    s3_env
    mkdir -p "$BACKUP_DIR/restore"
    rclone copy "$(remote "$2")" "$BACKUP_DIR/restore/"
    echo "$BACKUP_DIR/restore/$(basename "$2")"
    ;;
  s3-check)
    s3_enabled || {
      echo "S3 is not configured (BACKUP_S3_ENDPOINT/BUCKET/ACCESS_KEY/SECRET_KEY)" >&2
      exit 1
    }
    s3_env
    rclone lsd "arvan:${BACKUP_S3_BUCKET}" >/dev/null && echo "S3 OK: $(remote)"
    ;;
  *)
    echo "unknown command: $cmd" >&2
    exit 2
    ;;
esac
